"""
Examples of TTY command presets for a variety of GNSS and related devices

Copy those required to your *.json configuration file and invoke them
via the TTY Command dialog.

Created on 30 May 2025

:author: semuadmin
:copyright: 2025 SEMU Consulting
:license: BSD 3-Clause
"""

# ******************************************
# Septentrio Mosaic X5 Receiver
#
# Send an "Initialise Command Mode" string
# before sending further commands.
#
# NOT AN EXHAUSTIVE LIST
# Full details in https://www.septentrio.com/resources/mosaic-X5/mosaic-X5+Firmware+v4.14.10.1+Reference+Guide.pdf
# ******************************************
{
    "ttypresets_l": [
        "Initialise Command Mode; SSSSSSSSSS",
        "Display Help for all available commands; help, Overview",
        "Display Help for getReceiverCapabilities command; help, getReceiverCapabilities",
        "Display Help for getReceiverCapabilities command; help, grc",
        "List contents of current configuration file; lcf, Current",
        "Save current configuration to boot file; eccf, Current, Boot",
        "List receiver capabilities; grc",
        "Get command line interface version; gri",
        "List Current NMEA outputs; gno",
        "Enable NMEA messages; sno, Stream1, COM1, GGA+GSA+GLL+GSV+RMC+VTG, sec1",
        "Disable NMEA messages; sno, Stream1, none, none, off",
        "Enable Group stream; ssgp, Group1, MeasEpoch+PVTCartesian+DOP; sso, Stream2, COM1, Group1, sec1",
        "Disable Group stream; sso, Stream2, none, none, off",
        "Output next Measurement Epoch; esoc, COM1, MeasEpoch",
        "Enable PVTGeod stream; sso, Stream2, COM1, PVTGeod, sec1",
        "Enable Status stream; sso, Stream2, COM1, Status, sec1",
        "Enable RTCM3 messages on COM2 in base station mode;sr3o, COM2, RTCM1001+RTCM1002+RTCM1005+RTCM1006; sdio, COM2, , RTCMv3",
        "List Known Antenna Phase Centres; lai, Overview",
        "Turn ethernet interface on; seth, on",
        "Set Fixed Base Station Mode;setDataInOut,COM1, ,RTCMv3;setRTCMv3Formatting,1234;setStaticPosGeodetic,Geodetic1,37.23345,-115.81513,15;setPVTMode,Static, ,Geodetic1",
        "Set Survey-In Base Station Mode;setDataInOut,COM1, ,RTCMv3;setRTCMv3Formatting,1234;setPVTMode,Static, ,auto",
        "Stop RTCM output;setDataInOut,COM1, ,none",
        "Soft Reset to Factory Defaults;erst,soft,config",
        "List antenna information; lai, Overview",
        "List specific antenna information; lai, 'AERAT2775_159 SPKE'",
        "List command help; help, Overview",
        "Help getReceiverCapabilities; help, getReceiverCapabilities",
        "Help getReceiverCapabilities; help, grc",
        "Description; smp, TestMarker",
        "List configuration file; lcf, Current",
        "Execute copy configuration file; eccf, Current, Boot",
        "Execute copy configuration file; eccf, User1, Current",
        "Set ethernet mode; seth, on",
        "Execute FTP upgrade; efup, myftp.com, /tst.suf, user, password",
        "Set GPIO functionality; sgpf, GP2, Output, , LevelHigh",
        "List internal file; lif, Permissions",
        "Set LED mode; slm, DIFFCORLED",
        "List MIB description generic; lmd, Overview",
        "List MIB description getReceiverCapabilities; lmd, grc",
        "Get receiver capabilities; grc",
        "Get receiver interface; gri",
        "Execute registered applications; era, com1, MyApp",
        "Execute reset receiver; erst, soft, none",
        "Set USB internet access; suia, on",
        "Execute power mode; epwm, Standby",
        "List current user; lcu",
        "Login; login, admin, admin",
        "Logout; logout",
        "Set default access level; sdal, User, none, User, none, User",
        "Get user access level; sua1, User3, Mildred, mypwd, Viewer, AAAAE2VjZHa9YSdPMw",
        "Set calibration common delay; scco, 65.4",
        "Set calibration signal delay; scsi, GPSL5+GALE5a, -2.56",
        "Set channel allocation; sca, Ch05, G01",
        "Get channel allocation; gca, Ch05",
        "Set CN0 mask; scm, GEOL1, 30",
        "Get CN0 mask; gcm, GEOL1",
        "Set multipath mitigation; smm, on, off",
        "Get multipath mitigation; gmm",
        "Set satellite tracking GPS; sst, GPS",
        "Set satellite tracking all SBAS; sst, +SBAS",
        "Set satellite tracking remove SBAS S120; sst, -S120",
        "Set signal tracking; snt, GPSL1CA+GEOL1",
        "Get signal tracking; gnt",
        "Set smoothing interval; ssi, GPSL1CA, 300",
        "Get smoothing interval; gsi, GPSL1CA",
        "Set tracking loop parameters; stlp, GPSL1CA, 0.20, 12, , , off",
        "Get tracking loop parameters; gtlp, GPSL1CA",
        "Set AGC mode; sam, all, manual, 30",
        "Get AGC mode; gam, all",
        "Set baseband sampling mode; sbbs, BeforeIM",
        "Get baseband sampling mode; gbbs",
        "Set notch filtering; snf, Notch1, manual, 1227.0, 30",
        "Get notch filtering; gnf, Notch1",
        "Set wideband interference mitigation; swbi, on",
        "Get wideband interference mitigation; gwbi",
        "Set antenna offset; sao, Main, 0.1, 0.0, 1.3, 'AERAT2775_159 SPKE', 5684, 0",
        "Get antenna offset; gao, Main",
        "Set differential correction max age; sdca, 10",
        "Get differential correction max age; gdca",
        "Set differential correction usage; sdcu, LowLatency, 5.0, manual, 1011, off, 1, 10000",
        "Get differential correction usage; gdcu",
        "Set elevation mask; sem, PVT, 15",
        "Get elevation mask; gem, PVT",
        "Set geoid undulation; sgu, manual, 25.3",
        "Get geoid undulation; ggu",
        "Set health mask; shm, Tracking, off",
        "Get health mask; ghm",
        "Set ionosphere model; sim, off",
        "Get ionosphere model; gim",
        "Set magnetic variance; smv, manual, 1.1",
        "Get magnetic variance; gmv",
        "Set network RTK config; snrc, VRS",
        "Get network RTK config; gnrc",
        "Set PVT mode rover; spm, Rover, StandAlone+RTK",
        "Get PVT mode; gpm",
        "Set static position geodesic; sspg, Geodetic1, 50.5209, 4.4245, 113.3",
        "Set PVT mode static; spm, Static, , Geodetic1",
        "Set RAIM levels; srl, on, -4, -4, -6",
        "Get RAIM levels; grl",
        "Set RAIM off; srl, off",
        "Set receiver dynamics; srd, High, Automotive",
        "Get receiver dynamics; grd",
        "Execute receiver nav filter; ernf, PVT",
        "Get receiver nav filter; grnf",
        "Set satellite usage GPS; ssu, GPS",
        "Get satellite usage; gsu",
        "Set satellite usage all SBAS; ssu, +SBAS",
        "Set satellite usage remove SBAS S120; ssu, -S120",
        "Set SBAS corrections; ssbc, S122, Test",
        "Get SBAS corrections; gsbc",
        "Set signal usage; snu, GPSL1CA, GPSL1CA",
        "Get signal usage; gnu",
        "Set static position cartesian; sspc, Cartesian1, 4019952.028, 331452.954, 4924307.458",
        "Get static position cartesian; gspc, Cartesian1",
    ],
}

# ******************************************
# Feyman IM19 IMU with Tilt Compensation
#
# Full details in http://www.feymani.com/en/uploadfile/2023/1008/20231008072903360.pdf
# ******************************************
{
    "ttypresets_l": [
        "Tilt Survey Setup; AT+LOAD_DEFAULT; AT+GNSS_PORT=PHYSICAL_UART2; AT+NASC_OUTPUT=UART1,ON; AT+LEVER_ARM2=0.0057,-0.0732,-0.0645; AT+CLUB_VECTOR=0,0,1.865; AT+INSTALL_ANGLE=0,180,0; AT+GNSS_CARD=OEM; AT+WORK_MODE=408; AT+CORRECT_HOLDER=ENABLE; AT+SET_PPS_EDGE=RISING; AT+AHRS=ENABLE; AT+MAG_AUTO_SAVE=ENABLE; AT+SAVE_ALL",
        "System reset CONFIRM; AT+SYSTEM_RESET",
        "Save the parameters CONFIRM AT+SAVE_ALL",
        "Update module firmware, see attachment for protocols; AT+UPDATE_APP",
        "Update Bootloader, see attachment for protocols; AT+UPDATE_BOOT",
        "Set the GNSS RTK receiver type; AT+GNSS_CARD=OEM",
        "Read parameters (SYSTEM/ALL); AT+READ_PARA=SYSTEM/ALL",
        "Loading default parameters; AT+LOAD_DEFAULT",
        "Installation angle estimation in tilt measurement applications; AT+AUTO_FIX=ENABLE/DISABLE",
        "Set the RTK pole vector to map the position to the end of the RTK pole; AT+CLUB_VECTOR=X,Y,Z",
        "Binary NAVI positioning output; AT+NAVI_OUTPUT=UART1,ON/OFF",
        "Ascii type NAVI positioning output; AT+NASC_OUTPUT=UART1,ON/OFF",
        "MEMS raw output; AT+MEMS_OUTPUT=UART1,ON/OFF",
        "GNSS raw output; AT+GNSS_OUTPUT=UART1,ON/OFF",
        "Set the lever arm; AT+LEVER_ARM=X,Y,Z",
        "Query whether time is synchronized between MEMS and GNSS; AT+CHECK_SYNC",
        "High-rate mode setting; AT+HIGH_RATE=ENABLE/DISABLE",
        "Module activation; AT+ACTIVATE_KEY=KEY",
        "Set the initial alignment speed threshold; AT+ALIGN_VEL=1.0",
        "Query the Firmware version; AT+VERSION",
        "Set GNSS serial port; AT+GNSS_PORT=PHYSICAL_UART2",
        "Set the module working mode; AT+WORK_MODE=X",
        "Set the module installation angle; AT+INSTALL_ANGLE=X,Y,Z",
        "Query the serial port number; AT+THIS_PORT",
        "Causes the filter to enter or exit stop mode; AT+FILTER_STOP=ENABLE/DISABLE",
        "UART n enters or exits the loopback mode; AT+LOOP_BACK=UARTn/NONE",
        "Filter Reset; AT+FILTER_RESET",
        "Check firmware CRC, N=firmware size; AT+CHECK_CRC=N",
        "Turn on or off RTK pole length compensation; AT+CORRECT_HOLDER=ENABLE/DISABLE",
        "Disable the output of all messages over the serial port x; AT+DISABLE_OUTPUT=UARTx",
        "Factory calibration command; AT+CALIBRATE_MODE2=STEP1/STEP2",
    ],
}
