"""
Examples of TTY command presets for a variety of GNSS and related devices

Copy those required to your *.json configuration file and invoke them
via the TTY Command dialog.

Created on 30 May 2025

:author: semuadmin
:copyright: 2025 SEMU Consulting
:license: BSD 3-Clause
"""

# ******************************************
# Septentrio Mosaic X5 Receiver
#
# Send an "Initialise Command Mode" string
# before sending further commands.
#
# Full details in https://www.septentrio.com/resources/mosaic-X5/mosaic-X5+Firmware+v4.14.10.1+Reference+Guide.pdf
# ******************************************
{
    "ttypresets_l": [
        "Initialise Command Mode; SSSSSSSSSS",
        "Display Help for all available commands; help, Overview",
        "Display Help for getReceiverCapabilities command; help, getReceiverCapabilities",
        "Display Help for getReceiverCapabilities command; help, grc",
        "List contents of current configuration file; lcf, Current",
        "Save current configuration to boot file; eccf, Current, Boot",
        "List receiver capabilities; grc",
        "Get command line interface version; gri",
        "List Current NMEA outputs; gno",
        "Enable NMEA messages; sno, Stream1, COM1, GGA+GSA+GLL+GSV+RMC+VTG, sec1",
        "Disable NMEA messages; sno, Stream1, none, none, off",
        "Enable Group stream; ssgp, Group1, MeasEpoch+PVTCartesian+DOP; sso, Stream2, COM1, Group1, sec1",
        "Disable Group stream; sso, Stream2, none, none, off",
        "Output next Measurement Epoch; esoc, COM1, MeasEpoch",
        "Enable PVTGeod stream; sso, Stream2, COM1, PVTGeod, sec1",
        "Enable Status stream; sso, Stream2, COM1, Status, sec1",
        "Enable RTCM3 messages on COM2 in base station mode;sr3o, COM2, RTCM1001+RTCM1002+RTCM1005+RTCM1006; sdio, COM2, , RTCMv3",
        "List Known Antenna Phase Centres; lai, Overview",
        "Turn ethernet interface on; seth, on",
        "Set Fixed Base Station Mode;setDataInOut,COM1, ,RTCMv3;setRTCMv3Formatting,1234;setStaticPosGeodetic,Geodetic1,37.23345,-115.81513,15;setPVTMode,Static, ,Geodetic1",
        "Set Survey-In Base Station Mode;setDataInOut,COM1, ,RTCMv3;setRTCMv3Formatting,1234;setPVTMode,Static, ,auto",
        "Stop RTCM output;setDataInOut,COM1, ,none",
        "Soft Reset to Factory Defaults;erst,soft,config",
        "List antenna information; lai, Overview",
        "List specific antenna information; lai, 'AERAT2775_159 SPKE'",
        "Get command help; help, Overview",
        "Get specific command help; help, getReceiverCapabilities",
        "Description; help, grc",
        "Description; smp, TestMarker",
        "Description; lcf, Current",
        "Description; eccf, Current, Boot",
        "Description; eccf, User1, Current",
        "Description; seth, on",
        "Description; efup, myftp.com, /tst.suf, user, password",
        "Description; sgpf, GP2, Output, , LevelHigh",
        "Description; lif, Permissions",
        "Description; slm, DIFFCORLED",
        "Description; lmd, Overview",
        "Description; lmd, grc",
        "Description; grc",
        "Description; gri",
        "Description; era, com1, MyApp",
        "Description; erst, soft, none",
        "Description; suia, on",
        "Description; epwm, Standby",
        "Description; lcu",
        "Description; login, admin, admin",
        "Description; lcu",
        "Description; sdal, User, none, User, none, User",
        "Description; login, admin, admin",
        "Description; login, foo, foo",
        "Description; sso, Stream1, COM1, MeasEpoch, sec1",
        "Description; login, admin, admin",
        "Description; sso, Stream1, COM1, PVTCartesian, sec1",
        "Logout; logout",
        "Description; scco, 65.4",
        "Description; scsi, GPSL5+GALE5a, -2.56",
        "Description; sca, Ch05, G01",
        "Description; gca, Ch05",
        "Description; scm, GEOL1, 30",
        "Description; gcm, GEOL1",
        "Description; smm, on, off",
        "Description; gmm",
        "Description; sst, GPS",
        "Description; sst, +SBAS",
        "Description; sst, -S120",
        "Description; snt, GPSL1CA+GEOL1",
        "Description; gnt",
        "Description; ssi, GPSL1CA, 300",
        "Description; gsi, GPSL1CA",
        "Description; stlp, GPSL1CA, 0.20, 12, , , off",
        "Description; sam, all, manual, 30",
        "Description; sbbs, BeforeIM",
        "Description; snf, Notch1, manual, 1227.0, 30",
        "Description; swbi, on",
        "Description; sao, Main, 0.1, 0.0, 1.3, 'AERAT2775_159 SPKE', 5684, 0",
        "Description; sdca, 10",
        "Description; sdcu, LowLatency, 5.0, manual, 1011, off, 1, 10000",
        "Description; sem, PVT, 15",
        "Description; sgu, manual, 25.3",
        "Description; ggu",
        "Description; shm, Tracking, off",
        "Description; ghm",
        "Description; sim, off",
        "Description; gim",
        "Description; smv, manual, 1.1",
        "Description; gmv",
        "Description; snrc, VRS",
        "Description; spm, Rover, StandAlone+RTK",
        "Description; sspg, Geodetic1, 50.5209, 4.4245, 113.3",
        "Description; spm, Static, , Geodetic1",
        "Description; srl, on, -4, -4, -6",
        "Description; srl, off",
        "Description; srd, High, Automotive",
        "Description; ernf, PVT",
        "Description; ssu, GPS",
        "Description; ssu, +SBAS",
        "Description; ssu, -S120",
        "Description; ssbc, S122, Test",
        "Description; snu, GPSL1CA, GPSL1CA",
        "Description; sspc, Cartesian1, 4019952.028, 331452.954, 4924307.458",
        "Description; spm, Static, , Cartesian1",
        "Description; sspg, Geodetic1, 50.86696443, 4.71347657, 114.880",
        "Description; spm, Static, , Geodetic1",
        "Description; stm, MOPS, MOPS",
        "Description; gtm",
        "Description; stp, 25, 1013, 60",
        "Description; lstGalOSNMAPublicKeys",
        "Description; sou, strict",
        "Description; sal, Base, manual, 0, -1, 0.1",
        "Description; sto, 93.2, -0.4",
        "Description; sga, MovingBase",
        "Description; sgd, ETRS89",
        "Description; sue, User1, 6378388, 297",
        "Description; smtv, lt1, 10.904, 156.341, 1.3, 1.34, 1.34",
        "Description; slco, NONE, lt1",
        "Description; llc, Overview",
        "Description; scst, msec1, off",
        "Description; sep, EventA, High2Low, 10",
        "Description; snc, on, pool.ntp.org",
        "Description; sntp, on",
        "Description; spps, sec1, Low2High, 23.40, GPS, 60, 0.1",
        "Description; sptp, on",
        "Description; stss, EventB",
        "Description; sts, GPS",
        "Description; smp, Test, 356, GEODETIC, TST1, 0, 0, BEL",
        "Description; soc, 'Data taken with choke ring antenna'",
        "Description; goc",
        "Description; sop, TestObserver, TestAgency",
        "Description; gop",
        "Description; scia, on",
        "Description; scs, COM1, baud19200, bits8, No, bit1, RTS|CTS",
        "Description; scda, on",
        "Description; sdcm, DC1, ASCII",
        "Description; sdio, COM1, CMD",
        "Description; sdio, COM2, DC1, DC2",
        "Description; sdio, COM3, DC2, DC1",
        "Description; sdds, dyndns.org, Bart, MyPwd, rx1.dyndns-free.com, auto",
        "Description; eecm, COM2, 'A:Hello world!', none",
        "Description; shs, HTTP",
        "Description; sipf, on, 192.168.0.7 192.168.2.0/24",
        "Description; sipk, on, 20, 20, 20",
        "Description; sipp, 12345, 21",
        "Description; sirs, IPR1, 28785, TCP2Way, 192.168.10.5",
        "Description; siss, IPS1, 28785, UDP, 255.255.255.255",
        "Description; spe, COM2, 'A:Hello!%%CR%%LF', sec60",
        "Description; spe, COM2, 'H:48 65 6C 6C 6F 21 0D 0A', sec60",
        "Description; spe, COM2, 'A:Hello!%%CR%%LF', once",
        "Description; eccf, Current, Boot",
        "Description; spfw, Ethernet, PortList, '21 80 28784'",
        "Description; snmp, MP1, on, MyMP, Yes, MyUser, MyPwd, basic",
        "Description; smpf, MP1, manual, RAW%%CMNMEA, 'SBF (1s)%%CM NMEA (5s)'",
        "Description; sncs, on, 2101, default, 2102",
        "Description; sncu, User1, MyUser, MyPwd, all, 1",
        "Description; lnst, ntripcaster",
        "Description; sntt, NTR1, on, ''",
        "Description; sntt, NTR1, on, Aa:Bb:56:78:90:12: ... 78:90:12:34",
        "Description; sntt, NTR1, on, 'Aa Bb 56 78 90 12 ... 78 90 12 34'",
        "Description; sntt, NTR1, on, AaBb56789012 ... 78901234",
        "Description; enoc, COM1, GGA",
        "Description; sno, Stream1, COM1, GGA, sec1",
        "Description; sno, Stream2, COM1, RMC, msec100",
        "Description; gno",
        "Description; snp, 2, Mode2, off, 0.05",
        "Description; snti, GP",
        "Description; snv, v4x",
        "Description; smrf, OnlyRef",
        "Description; ssgp, Group1, MeasEpoch+PVTCartesian+DOP",
        "Description; sso, Stream1, COM1, Group1, sec1",
        "Description; esoc, COM1, MeasEpoch",
        "Description; sso, Stream1, COM1, MeasEpoch, msec100",
        "Description; sso, Stream2, COM1, PVTGeodetic, sec1",
        "Description; sr2c, , Tb",
        "Description; sr2h, 60, 0",
        "Description; sr2f, 345",
        "Description; gr2f",
        "Description; sr2i, RTCM22, 15",
        "Description; gr2i",
        "Description; sr2b, RTCM20|21, 2",
        "Description; gr2b",
        "Description; sr2m, Hello",
        "Description; sr2o, COM2, RTCM16",
        "Description; sdio, COM2, , RTCMv2",
        "Description; sr2o, COM2, RTCM3+RTCM18|19+RTCM22",
        "Description; sdio, COM2, , RTCMv2",
        "Description; sr2u, RTCM1+RTCM3",
        "Description; sdcu, , , manual, 1011",
        "Description; sr3t, manual, '4258'",
        "Description; sr3i, RTCM1001|2, 10",
        "Description; sr3d, 2",
        "Description; sr3i, RTCM1001|2, 2",
        "Description; sr3m, Hello",
        "Description; sr3o, COM2, RTCM1029",
        "Description; sdio, COM2, , RTCMv3",
        "Description; sr3o, COM2, RTCM1001+RTCM1002+RTCM1005+RTCM1006",
        "Description; sdio, COM2, , RTCMv3",
        "Description; sr3u, RTCM1001+RTCM1002",
        "Description; sdcu, , , manual, 1011",
        "Description; sc2f, 12",
        "Description; gc2f",
        "Description; sc2i, CMR0, 2",
        "Description; gc2i",
        "Description; sc2m, Hello",
        "Description; sc2o, COM2, CMR2",
        "Description; sdio, COM2, , CMRv2",
        "Description; sc2o, COM2, CMR0",
        "Description; sdio, COM2, , CMRv2",
        "Description; sc2u, CMR0",
        "Description; sdcu, , , manual, 12",
        "Description; sdfa, DSK1, StopLogging",
        "Description; gdfa",
        "Description; ldi, DSK1",
        "Description; sfn, DSK1, FileName, mytest",
        "Description; sfno, on",
        "Description; lrf, DSK1, log.sbf",
        "Description; lrf, DSK1, log.sbf",
        "Description; erf, DSK1, 03298/ATRX2980.03_",
        "Description; erf, DSK1, all",
        "Description; srxl, DSK1, hour24, sec30, GPSL1CA",
        "Description; suoc, off",
        "Description; sfpr, ftp.mydomain.com, mydata/%Y%m%d, myname, mypwd",
        "Description; sfps, ftp.mydomain.com, mydata/%Y%m%d, myname, mypwd",
        "Description; efpt, myftp.com, mydata/%Y%m%d, myname, mypwd",
        "Description; llbb",
        "Description; slbb, User1, 1537460000, baud1200, 25East, E, Enabled",
        "Description; slcs, A5A5, 0101, on",
        "Description; slnd, NTR1",
    ],
}

# ******************************************
# Feyman IM19 IMU with Tilt Compensation
#
# Full details in http://www.feymani.com/en/uploadfile/2023/1008/20231008072903360.pdf
# ******************************************
{
    "ttypresets_l": [
        "Tilt Survey Setup; AT+LOAD_DEFAULT; AT+GNSS_PORT=PHYSICAL_UART2; AT+NASC_OUTPUT=UART1,ON; AT+LEVER_ARM2=0.0057,-0.0732,-0.0645; AT+CLUB_VECTOR=0,0,1.865; AT+INSTALL_ANGLE=0,180,0; AT+GNSS_CARD=OEM; AT+WORK_MODE=408; AT+CORRECT_HOLDER=ENABLE; AT+SET_PPS_EDGE=RISING; AT+AHRS=ENABLE; AT+MAG_AUTO_SAVE=ENABLE; AT+SAVE_ALL",
        "System reset CONFIRM; AT+SYSTEM_RESET",
        "Save the parameters CONFIRM AT+SAVE_ALL",
        "Update module firmware, see attachment for protocols; AT+UPDATE_APP",
        "Update Bootloader, see attachment for protocols; AT+UPDATE_BOOT",
        "Set the GNSS RTK receiver type; AT+GNSS_CARD=OEM",
        "Read parameters (SYSTEM/ALL); AT+READ_PARA=SYSTEM/ALL",
        "Loading default parameters; AT+LOAD_DEFAULT",
        "Installation angle estimation in tilt measurement applications; AT+AUTO_FIX=ENABLE/DISABLE",
        "Set the RTK pole vector to map the position to the end of the RTK pole; AT+CLUB_VECTOR=X,Y,Z",
        "Binary NAVI positioning output; AT+NAVI_OUTPUT=UART1,ON/OFF",
        "Ascii type NAVI positioning output; AT+NASC_OUTPUT=UART1,ON/OFF",
        "MEMS raw output; AT+MEMS_OUTPUT=UART1,ON/OFF",
        "GNSS raw output; AT+GNSS_OUTPUT=UART1,ON/OFF",
        "Set the lever arm; AT+LEVER_ARM=X,Y,Z",
        "Query whether time is synchronized between MEMS and GNSS; AT+CHECK_SYNC",
        "High-rate mode setting; AT+HIGH_RATE=ENABLE/DISABLE",
        "Module activation; AT+ACTIVATE_KEY=KEY",
        "Set the initial alignment speed threshold; AT+ALIGN_VEL=1.0",
        "Query the Firmware version; AT+VERSION",
        "Set GNSS serial port; AT+GNSS_PORT=PHYSICAL_UART2",
        "Set the module working mode; AT+WORK_MODE=X",
        "Set the module installation angle; AT+INSTALL_ANGLE=X,Y,Z",
        "Query the serial port number; AT+THIS_PORT",
        "Causes the filter to enter or exit stop mode; AT+FILTER_STOP=ENABLE/DISABLE",
        "UART n enters or exits the loopback mode; AT+LOOP_BACK=UARTn/NONE",
        "Filter Reset; AT+FILTER_RESET",
        "Check firmware CRC, N=firmware size; AT+CHECK_CRC=N",
        "Turn on or off RTK pole length compensation; AT+CORRECT_HOLDER=ENABLE/DISABLE",
        "Disable the output of all messages over the serial port x; AT+DISABLE_OUTPUT=UARTx",
        "Factory calibration command; AT+CALIBRATE_MODE2=STEP1/STEP2",
    ],
}
