name: checkpr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15.0-rc.2"]

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deploy dependencies
        run: pip install --group deploy
      - name: Install code dependencies
        run: pip install .
      - name: Install dill 0.4.2.dev for Python 3.15
        run: pip install --force-reinstall git+https://github.com/uqfoundation/dill.git
      - name: Lint with pylint
        run: pylint -E src
      - name: Scan security vulnerabilities with bandit
        run: bandit -c pyproject.toml -r .
      - name: Generate coverage report
        run: pytest
